### ISSUE TITLE
MITM

### ISSUE THREAD

**Issue by ghost** [nametoolong/oregano#2]
If the victim and I are in the same wlan,this tool use arp spoof to work.
And break the victim's tor connection.
Correct?

**Comment by nametoolong** [comment]
Not exactly. This tool does not include the ARP spoofing tool (roll your own using scapy) and **cannot** break Tor connections completely. This tool only allows you to tamper a **bridge** connection and do something sneaky such as the "one cell is enough" attack. Normal Tor connections validate peer identity with keys in the consensus and thus is almost impossible to break.

**Comment by ghost** [comment]
How about Sybil attack?

**Comment by nametoolong** [comment]
It is relatively difficult to mount a Sybil attack on the Tor network: it takes a considerable amount of time for a new relay to become a guard relay. Therefore, it wouldn't be worth the hassle to implement Sybil attack functionality in this tiny tool. See [The lifecycle of a new relay](https://blog.torproject.org/lifecycle-new-relay) for details.
This tool is not particularly useful under most scenarios. Only when your target is connecting with vanilla bridges can it be useful, and it can only strip the outermost layer of onionskin, so it wouldn't put you to an advantageous position to deanonymize the victim, but rather help with Tor research.

**Comment by ghost** [comment]
Thanks for your responds.
